import turtle

turtle.pensize(5)
turtle.circle(120)
turtle.penup()
turtle.goto(0,20)
turtle.down()
turtle.pensize(5)
turtle.circle(100)
turtle.penup()
turtle.goto(0,40)
turtle.down()
turtle.pensize(5)
turtle.circle(80)
turtle.penup()
turtle.goto(0,60)
turtle.down()
turtle.pensize(5)
turtle.circle(60)
turtle.penup()
turtle.goto(0,80)
turtle.down()
turtle.pensize(5)
turtle.circle(40)
turtle.penup()
turtle.goto(0,100)
turtle.down()
turtle.down()
turtle.pensize(5)
turtle.circle(80)
turtle.penup()
turtle.goto(0,60)
turtle.down()
turtle.pensize(5)
turtle.circle(60)
turtle.penup()
turtle.goto(0,80)
turtle.down()
turtle.pensize(5)
turtle.circle(40)
turtle.penup()
turtle.goto(0,100)
turtle.down()
import turtle

turtle.pensize(5)
turtle.circle(120)
turtle.penup()
turtle.goto(0,20)
turtle.down()
turtle.pensize(5)
turtle.circle(100)
turtle.penup()
turtle.goto(0,40)
turtle.down()
turtle.pensize(5)
turtle.circle(80)
turtle.penup()
turtle.goto(0,60)
turtle.down()
turtle.pensize(5)
turtle.circle(60)
turtle.penup()
turtle.goto(0,80)
turtle.down()
turtle.pensize(5)
turtle.circle(40)
turtle.penup()
turtle.goto(0,100)
turtle.down()
import turtle

turtle.pensize(5)
turtle.circle(120)
turtle.penup()
turtle.goto(0,20)
turtle.down()
turtle.pensize(5)
turtle.circle(100)
turtle.penup()
turtle.goto(0,40)
turtle.down()
turtle.pensize(5)
turtle.circle(80)
turtle.penup()
turtle.goto(0,60)
turtle.down()
turtle.pensize(5)
turtle.circle(60)
turtle.penup()
turtle.goto(0,80)
turtle.down()
turtle.pensize(5)
turtle.circle(40)
turtle.penup()
turtle.goto(0,100)
turtle.down()
import turtle

turtle.pensize(5)
turtle.circle(120)
turtle.penup()
turtle.goto(0,20)
turtle.down()
turtle.pensize(5)
turtle.circle(100)
turtle.penup()
turtle.goto(0,40)
turtle.down()
turtle.pensize(5)
turtle.circle(80)
turtle.penup()
turtle.goto(0,60)
turtle.down()
turtle.pensize(5)
turtle.circle(60)
turtle.penup()
turtle.goto(0,80)
turtle.down()
turtle.pensize(5)
turtle.circle(40)
turtle.penup()
turtle.goto(0,100)
turtle.down()
















