print('hello world')
print(999.0*6.65)
print('  *  ')
print(' * *')
print('*****')
print(18/(2*3))
print('         望庐山瀑布')
print('          [唐]李白         '   )
print('日照香炉生紫烟,遥看瀑布挂前川。')
print('飞流直下三千尺,疑是银河落九天。')